server:
  port: 8081

spring:
  application:
    name: personal-data-service
  
  artemis:
    mode: native
    host: localhost
    port: 61616
    user: artemis
    password: simetraehcapa
    
logging:
  level:
    com.example.personal: DEBUG
    org.springframework: INFO 