server:
  port: 8082

spring:
  application:
    name: contact-service
  
  artemis:
    mode: native
    host: localhost
    port: 61616
    user: artemis
    password: simetraehcapa
    
logging:
  level:
    com.example.contact: DEBUG
    org.springframework: INFO 